# Copyright 2025 Project Astra Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# MODIFICATIONS (Astra project):
#   - Phase 4: Intel SGX TEE backend via Gramine Library OS.
#   - Gramine (formerly Graphene) runs unmodified Python inside an SGX enclave.
#   - This module provides the Python-side backend that interfaces with
#     the Gramine manifest and the underlying SGX primitives.

"""
Intel SGX TEE backend using Gramine Library OS.

Gramine runs Python in a hardware-isolated SGX enclave without
requiring code changes to the Python interpreter.  A manifest
file (``astra.manifest.template``) declares which files are
visible inside the enclave.

Requirements:
  - Intel CPU with SGX (6th-gen Core or newer)
  - SGX enabled in BIOS (Software Controlled or Enabled)
  - Gramine installed (``gramine-direct``, ``gramine-sgx``)
  - Intel SGX SDK + PSW for quote generation

Phase 4 delivers the interface skeleton.  Production deployment
needs SGX hardware and the Gramine toolchain.  See docs/TEE.md
for setup instructions.

Usage::

    from astra.tee import register_backend
    from astra.tee.gramine import GramineBackend

    sgx = GramineBackend(build_dir="/opt/astra/enclave")
    register_backend("sgx", sgx)

    if sgx.status() == TEEStatus.AVAILABLE:
        attestation = sgx.attest()
        sealed_key = sgx.seal(my_secret_bytes)

    from astra.tee import get_tee_backend
    tee = get_tee_backend("sgx")
"""

from __future__ import annotations

import hashlib
import os
import platform
import subprocess
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Optional
import logging

from . import (
    AttestationReport,
    SealedBlob,
    TEEBackend,
    TEEStatus,
)

logger = logging.getLogger(__name__)


# ------------------------------------------------------------------ #
# Gramine manifest template                                              #
# ------------------------------------------------------------------ #

GRAMINE_MANIFEST_TEMPLATE = """\
# Astra Gramine manifest for SGX enclave
# Generated by astra.tee.gramine.GramineBackend
loader.entrypoint = "file:{{ gramine.libos }}"
libos.entrypoint = "{{ python_path }}"
loader.env.LD_LIBRARY_PATH = "/lib:/usr/lib:{{ python_lib }}"

# Python inside enclave
fs.mounts = [
  { type = "chroot", path = "/lib", uri = "file:{{ host_lib }}" },
  { type = "chroot", path = "/usr/lib", uri = "file:/usr/lib" },
  { path = "{{ venv_path }}", uri = "file:{{ venv_path }}" },
  { path = "{{ astra_path }}", uri = "file:{{ astra_path }}" },
]

sgx.enclave_size = "{{ enclave_size }}"
sgx.thread_num = {{ thread_count }}
sgx.nonpie_binary = true
sgx.debug = {{ sgx_debug }}
sgx.edmm_enable = {{ edmm_enable }}

sgx.trusted_files = [
  "file:{{ python_path }}",
  "file:{{ astra_path }}/astra/__init__.py",
]

sgx.allowed_files = [
  "file:{{ tmp_dir }}",
]
"""


@dataclass
class GramineConfig:
    """Configuration for a Gramine SGX enclave."""
    build_dir: str = "/opt/astra/enclave"
    python_path: str = "/usr/bin/python3"
    python_lib: str = "/usr/lib/python3.11"
    venv_path: str = "/opt/astra/.venv"
    astra_path: str = "/opt/astra"
    enclave_size: str = "8G"
    thread_count: int = 8
    sgx_debug: bool = True          # Set to False in production
    edmm_enable: bool = False       # Enclave Dynamic Memory Management
    host_lib: str = "/lib"


# ------------------------------------------------------------------ #
# Gramine backend                                                        #
# ------------------------------------------------------------------ #

class GramineBackend(TEEBackend):
    """Intel SGX TEE backend via the Gramine Library OS.

    When running on SGX-capable hardware, this backend manages
    the enclave lifecycle (create, attest, seal, unseal).
    On non-SGX machines it reports TEEStatus.UNAVAILABLE so the
    application can fall back to software-only mode.

    Parameters
    ----------
    config : GramineConfig
        Enclave build parameters (paths, sizes, threads).
    """

    def __init__(self, config: Optional[GramineConfig] = None) -> None:
        self._cfg = config or GramineConfig()
        self._detected = False
        self._status: Optional[TEEStatus] = None
        self._enclave_measurement: str = ""

    # ------------------------------------------------------------------ #
    # Detection                                                              #
    # ------------------------------------------------------------------ #

    def _detect_sgx(self) -> TEEStatus:
        """Check whether SGX is available on this machine.

        Detection strategy (multiple fallbacks):
          1. Check /dev/sgx_enclave or /dev/isgx
          2. Check CPUID (Windows: registry, Linux: /proc/cpuinfo)
          3. Check for gramine-sgx in PATH
        """
        system = platform.system()

        # Check SGX device nodes (Linux)
        if system == "Linux":
            if os.path.exists("/dev/sgx_enclave") or os.path.exists("/dev/isgx"):
                pass  # device present, continue checking
            else:
                # Check /proc/cpuinfo for sgx flag
                try:
                    with open("/proc/cpuinfo") as f:
                        if "sgx" not in f.read().lower():
                            return TEEStatus.UNAVAILABLE
                except Exception:
                    return TEEStatus.UNKNOWN

        # Check for Gramine toolchain
        try:
            subprocess.run(
                ["gramine-sgx", "--version"],
                capture_output=True,
                timeout=5,
            )
        except (FileNotFoundError, subprocess.TimeoutExpired):
            self._enclave_measurement = self._compute_dummy_mrenclave()
            return TEEStatus.NOT_CONFIGURED

        # Compute dummy measurement for the manifest
        self._enclave_measurement = self._compute_dummy_mrenclave()

        return TEEStatus.AVAILABLE

    def _compute_dummy_mrenclave(self) -> str:
        """Compute a deterministic MRENCLAVE for the manifest.

        In production, GRAMINE generates this during ``gramine-sgx-sign``.
        Here we hash the manifest template to provide a placeholder
        that can be verified against a known-good value.
        """
        manifest = GRAMINE_MANIFEST_TEMPLATE.replace(
            "{{ python_path }}", self._cfg.python_path
        ).replace("{{ python_lib }}", self._cfg.python_lib)
        return hashlib.sha256(manifest.encode()).hexdigest()[:64]

    # ------------------------------------------------------------------ #
    # TEEBackend interface                                                   #
    # ------------------------------------------------------------------ #

    def status(self) -> TEEStatus:
        if self._status is None:
            self._status = self._detect_sgx()
        return self._status

    def attest(self) -> AttestationReport:
        """Generate an SGX attestation report (QUOTE).

        Calls ``gramine-sgx-get-token`` to retrieve a DCAP quote.
        Falls back to a simulated placeholder on non-SGX hardware.
        """
        status = self.status()
        is_valid = status == TEEStatus.AVAILABLE

        report = AttestationReport(
            tee_type="sgx",
            is_valid=is_valid,
            measurement=self._enclave_measurement or "0000" * 16,
            timestamp=time.time(),
            details={
                "hardware": status.value,
                "driver": "gramine",
                "quote_type": "ECDSA" if is_valid else "placeholder",
                "sgx_version": self._get_sgx_version(),
            },
        )

        if is_valid:
            quote = self.get_quote()
            report.details["quote_size"] = len(quote)
            report.details["quote_hex"] = quote.hex()[:64] + "..."

        return report

    def seal(self, plaintext: bytes) -> SealedBlob:
        """Seal data to this SGX enclave.

        Production: calls SGX EGETKEY to derive an enclave-specific
        sealing key.  Here: placeholder AES-GCM with mock key.
        """
        import secrets
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM

        # Derive a mock sealing key from the enclave measurement
        key_material = hashlib.sha256(
            self._enclave_measurement.encode()
        ).digest()
        nonce = secrets.token_bytes(12)

        try:
            aesgcm = AESGCM(key_material)
            ciphertext = aesgcm.encrypt(nonce, plaintext, None)
        except ImportError:
            # cryptography not installed — fallback to plain base64
            import base64
            ciphertext = base64.b64encode(plaintext)

        return SealedBlob(
            ciphertext=nonce + ciphertext,
            tee_type="sgx",
            api_version="1.0",
        )

    def unseal(self, blob: SealedBlob) -> bytes:
        """Decrypt a sealed blob inside the enclave."""
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM

        nonce = blob.ciphertext[:12]
        ct = blob.ciphertext[12:]

        key_material = hashlib.sha256(
            self._enclave_measurement.encode()
        ).digest()
        aesgcm = AESGCM(key_material)
        return aesgcm.decrypt(nonce, ct, None)

    def get_quote(self) -> bytes:
        """Retrieve a raw SGX DCAP quote for verification.

        Production: runs ``gramine-sgx-get-token`` and collects
        the ECDSA-signed quote from the Quoting Enclave.

        Phase 4: returns a zero-filled placeholder.
        """
        status = self.status()
        if status != TEEStatus.AVAILABLE:
            logger.warning("SGX unavailable — returning placeholder quote")
            return b"\\x00" * 1024
        try:
            result = subprocess.run(
                ["gramine-sgx-get-token", "--quote"],
                capture_output=True,
                timeout=10,
                cwd=self._cfg.build_dir,
            )
            return result.stdout
        except Exception:
            return b"\\x00" * 1024

    # ------------------------------------------------------------------ #
    # Helpers                                                                #
    # ------------------------------------------------------------------ #

    def _get_sgx_version(self) -> str:
        try:
            result = subprocess.run(
                ["gramine-sgx", "--version"],
                capture_output=True,
                text=True,
                timeout=5,
            )
            return result.stdout.strip().split("\n")[0]
        except Exception:
            return "unknown"

    def generate_manifest(self, output_path: str) -> None:
        """Write the Gramine manifest template to a file.

        The user must then run ``gramine-sgx-sign`` to produce
        the final signed manifest for the enclave.
        """
        manifest = (
            GRAMINE_MANIFEST_TEMPLATE
            .replace("{{ gramine.libos }}", "/usr/lib/gramine/libsysdb.so")
            .replace("{{ python_path }}", self._cfg.python_path)
            .replace("{{ python_lib }}", self._cfg.python_lib)
            .replace("{{ venv_path }}", self._cfg.venv_path)
            .replace("{{ astra_path }}", self._cfg.astra_path)
            .replace("{{ enclave_size }}", self._cfg.enclave_size)
            .replace("{{ thread_count }}", str(self._cfg.thread_count))
            .replace("{{ sgx_debug }}", str(self._cfg.sgx_debug).lower())
            .replace("{{ edmm_enable }}", str(self._cfg.edmm_enable).lower())
            .replace("{{ host_lib }}", self._cfg.host_lib)
            .replace("{{ tmp_dir }}", "/tmp")
        )
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w") as f:
            f.write(manifest)
        logger.info(f"Gramine manifest written to {output_path}")

    @property
    def config(self) -> GramineConfig:
        return self._cfg

    @property
    def enclave_measurement(self) -> str:
        """MRENCLAVE — the cryptographic identity of this enclave."""
        if not self._enclave_measurement:
            self._detect_sgx()
        return self._enclave_measurement
